#!/usr/bin/env python3
# Generates a GX I8 texture atlas containing ASCII + Cyrillic glyphs for Swiss,
# used by the UI font renderer to display languages the IPL ROM font cannot
# (e.g. Russian). Emits source/gui/cyrfont.c and source/gui/cyrfont.h.
#
# Glyph order / index mapping (see cyrGlyphIndex in cyrfont.c):
#   0..94   : ASCII 0x20..0x7E
#   95      : U+0401 CYRILLIC CAPITAL IO
#   96      : U+0451 CYRILLIC SMALL IO
#   97..160 : U+0410..U+044F (А..я)
#
# The atlas is stored as GX_TF_I8 (1 byte/texel, tiled 8x4). Glyph coverage is
# stored as intensity; for I8 formats GX replicates intensity to RGBA, so the
# TEV/blend setup used for the IPL font (texture alpha * raster alpha) renders
# an anti-aliased glyph in the requested colour with no changes.

import os
from PIL import Image, ImageFont, ImageDraw

FONT_PATH = "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"
FONT_SIZE = 20
CELL_H = 24              # matches the IPL ANSI font cell height

OUT_DIR = os.path.join(os.path.dirname(__file__), "..", "cube", "swiss", "source", "gui")

# Build the ordered codepoint list.
codepoints = []
for cp in range(0x20, 0x7F):
    codepoints.append(cp)
codepoints.append(0x0401)  # Ё
codepoints.append(0x0451)  # ё
for cp in range(0x0410, 0x0450):  # А..я
    codepoints.append(cp)

font = ImageFont.truetype(FONT_PATH, FONT_SIZE)
ascent, descent = font.getmetrics()
baseline = ascent
if ascent + descent > CELL_H:
    # Clip descenders slightly rather than shrink the whole face.
    pass

# Measure advances.
advances = []
for cp in codepoints:
    ch = chr(cp)
    adv = int(round(font.getlength(ch)))
    if adv < 1:
        adv = 1
    advances.append(adv)

CELL_W = max(advances) + 1        # +1 guard column so NEAREST sampling never bleeds
COLS = 16
ROWS = (len(codepoints) + COLS - 1) // COLS

# GX_TF_I8 is tiled in 8(wide) x 4(tall) blocks; pad the sheet to those multiples.
def round_up(v, m):
    return (v + m - 1) // m * m

TEX_W = round_up(CELL_W * COLS, 8)
TEX_H = round_up(CELL_H * ROWS, 4)

# Render all glyphs into a linear intensity image first.
sheet = Image.new("L", (TEX_W, TEX_H), 0)
draw = ImageDraw.Draw(sheet)
for i, cp in enumerate(codepoints):
    col = i % COLS
    row = i // COLS
    x0 = col * CELL_W
    y0 = row * CELL_H
    # anchor "ls" = left / baseline
    draw.text((x0, y0 + baseline), chr(cp), font=font, fill=255, anchor="ls")

px = sheet.load()

# Tile into GX_TF_I8 order: 8x4 texel tiles, tiles row-major, texels within a
# tile row-major.
out = bytearray()
for ty in range(0, TEX_H, 4):
    for tx in range(0, TEX_W, 8):
        for y in range(ty, ty + 4):
            for x in range(tx, tx + 8):
                out.append(px[x, y])

# Emit header.
os.makedirs(OUT_DIR, exist_ok=True)
with open(os.path.join(OUT_DIR, "cyrfont.h"), "w") as f:
    f.write("""/* cyrfont.h - generated by buildtools/gencyrfont.py, do not edit by hand.
   ASCII + Cyrillic glyph atlas (GX_TF_I8) for the Swiss UI font renderer. */
#ifndef CYRFONT_H
#define CYRFONT_H

#include <gctypes.h>

#define CYR_CELL_W %d
#define CYR_CELL_H %d
#define CYR_COLS   %d
#define CYR_ROWS   %d
#define CYR_TEX_W  %d
#define CYR_TEX_H  %d
#define CYR_GLYPH_COUNT %d

extern const u8 cyrFontData[%d];
extern const u8 cyrFontWidth[CYR_GLYPH_COUNT];

/* Maps a Unicode code point to an atlas glyph index, or the index of '?'
   when the code point is not present in the atlas. */
int cyrGlyphIndex(u32 codepoint);

#endif
""" % (CELL_W, CELL_H, COLS, ROWS, TEX_W, TEX_H, len(codepoints), len(out)))

# Emit source.
with open(os.path.join(OUT_DIR, "cyrfont.c"), "w") as f:
    f.write("/* cyrfont.c - generated by buildtools/gencyrfont.py, do not edit by hand. */\n")
    f.write('#include "cyrfont.h"\n\n')

    f.write("const u8 cyrFontWidth[CYR_GLYPH_COUNT] = {\n\t")
    for i, w in enumerate(advances):
        f.write("%d," % w)
        if (i + 1) % 16 == 0:
            f.write("\n\t")
    f.write("\n};\n\n")

    f.write("int cyrGlyphIndex(u32 cp) {\n")
    f.write("\tif (cp >= 0x20 && cp <= 0x7E) return (int)(cp - 0x20);\n")
    f.write("\tif (cp == 0x0401) return 95;\n")
    f.write("\tif (cp == 0x0451) return 96;\n")
    f.write("\tif (cp >= 0x0410 && cp <= 0x044F) return 97 + (int)(cp - 0x0410);\n")
    f.write("\treturn (int)('?' - 0x20);\n")
    f.write("}\n\n")

    f.write("const u8 cyrFontData[%d] __attribute__((aligned(32))) = {\n\t" % len(out))
    for i, b in enumerate(out):
        f.write("0x%02x," % b)
        if (i + 1) % 16 == 0:
            f.write("\n\t")
    f.write("\n};\n")

print("Generated cyrfont: %d glyphs, cell %dx%d, tex %dx%d, %d bytes" %
      (len(codepoints), CELL_W, CELL_H, TEX_W, TEX_H, len(out)))
