/* cyrfont.h - generated by buildtools/gencyrfont.py, do not edit by hand.
   ASCII + Cyrillic glyph atlas (GX_TF_I8) for the Swiss UI font renderer. */
#ifndef CYRFONT_H
#define CYRFONT_H

#include <gctypes.h>

#define CYR_CELL_W 23
#define CYR_CELL_H 24
#define CYR_COLS   16
#define CYR_ROWS   11
#define CYR_TEX_W  368
#define CYR_TEX_H  264
#define CYR_GLYPH_COUNT 161

extern const u8 cyrFontData[97152];
extern const u8 cyrFontWidth[CYR_GLYPH_COUNT];

/* Maps a Unicode code point to an atlas glyph index, or the index of '?'
   when the code point is not present in the atlas. */
int cyrGlyphIndex(u32 codepoint);

#endif
